<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <StartupObject>RapidFire_MasterServer.Program</StartupObject>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <AssemblyName>RapidFire_Master</AssemblyName>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.0.29" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\RapidFire_FPS_Mirror\Assets\aRapid Fire Project\Reference\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
